### ISSUE TITLE
AWS Image Links

### ISSUE THREAD

**Issue by chrieke** [SpaceNetChallenge/BuildingDetectors#1]
Thanks for sharing the repos!

The AWS Image links in both repos just direct to the AWS frontpage, could you give us the AMI ID and region or link directly to it? Thanks!

**Comment by toddstavish** [comment]
I am moving all of the source into the repos today. I'll have the AMIs available by next week.

**Comment by toddstavish** [comment]
AMIs are not looking doable. We plan to add dockerfiles for a few of the implementations and the new ones going forward.
